;NAME - NISHANT PANIGRAHY
;REGD. NO. - 2141016119
;SECTION - K
;BRANCH - CSE
;OBJECTIVE - LAB 4 (I a) FIND THE LARGEST NUMBER IN EACH ARRAY OF SIZE N

MOV AX, 0000H
MOV DS, AX
MOV SI, 2000H
MOV DI, 2050H
MOV CX, [SI]
INC SI
INC SI
MOV AL, [SI]
DEC CX
L1:INC SI 
MOV BL, [SI]
CMP AL, BL
JNC L2
MOV AL, BL
L2: LOOP L1
MOV [DI], AL
HLT