;NAME - NISHANT PANIGRAHY
;REGD. NO. - 2141016119
;SECTION - K
;BRANCH - CSE
;OBJECTIVE - LAB 4 (I) FIND THE LARGEST AND SMALLEST NUMBER IN EACH ARRAY OF SIZE N

MOV SI,5000H
MOV CX,05H
MOV AL,00H
LOOP1: CMP AL, [SI]
       JNC LOOP2
       MOV AL, [SI]
LOOP2: INC SI
       LOOP LOOP1
       MOV [SI],AL
HLT