;NAME - NISHANT PANIGRAHY
;REGD. NO. - 2141016119
;SECTION - K
;BRANCH - CSE
;OBJECTIVE - LAB 2 (III b) (DATA1 AND DATA2) OR (DATA1 XOR DATA2)

MOV AX, 0000H
MOV DS, AX
MOV SI, 2000H
MOV AL, [SI] ;DATA1
MOV CL, [SI]
MOV BL, [SI+01H] ;DATA2
AND AL, BL
XOR CL, BL
OR AL, CL
MOV [SI+02H], AL
HLT