;NAME - NISHANT PANIGRAHY
;REGD. NO. - 2141016119
;SECTION - K
;BRANCH - CSE
;OBJECTIVE - LAB 3 (I) FIND THE AVERAGE OF N 16-BIT NUMBERS

MOV AX, 0000H
MOV DS, AX
MOV SI, 2000H
MOV CX, [SI]
MOV BX, CX
MOV DX, 0000H
LOOP1: INC SI
       INC SI
       ADD AX, [SI]
       JNC LOOP2
       INC DX
LOOP2: DEC CX
       JNZ LOOP1
       INC SI
       INC SI
MOV [SI], AX
INC SI
INC SI
DIV BX
MOV [SI], AX
INC SI
INC SI 
MOV [SI], DX
HLT