;NAME - NISHANT PANIGRAHY
;REGD. NO. - 2141016119
;SECTION - K
;BRANCH - CSE
;OBJECTIVE - LAB 3 (II) COUNT THE NO. OF 1'S IN AN 8-BIT NUMBER

MOV AX, 0000H
MOV DS, AX
MOV BX, 2000H
MOV AL, [BX]
MOV CL, 08H
MOV CH, 00H
LOOP1: SHR AL, 01H
       JNC LOOP2
       INC CH
LOOP2: DEC CL
       JNZ LOOP1
       INC BX
MOV [BX],CH
HLT

