;NAME - NISHANT PANIGRAHY
;REGD. NO. - 2141016119
;SECTION - K
;BRANCH - CSE
;OBJECTIVE - LAB 3 (III) MOVE THE 16-BIT NUMBERS FROM ONE LOCATION TO ANOTHER

MOV AX, 0000H
MOV DS, AX
MOV SI, 5000H
MOV DI, 5020H
MOV DH, 05H
LOOP1: MOV CX, [SI] 
       INC SI
       INC SI
       MOV [DI],CX
       INC DI
       INC DI
       DEC DH
       JNZ LOOP1
HLT